### ISSUE TITLE
get symbol in angular library isn't right clickable

### ISSUE THREAD

**Issue by uforic** [sourcegraph/langserver-typescript#3]
Repro: https://sourcegraph.com/github.com/angular/angular/-/blob/modules/@angular/http/src/http.ts#L134

On the get method, try right clicking - you can't!

https://cl.ly/1w1U1J241819

What's weird is that request, post, and put work, just not delete and get.

**Comment by rothfels** [comment]
@uforic this is actually a problem in Sourcegraph, which prevents right clicks on any token that's not an `identifier` -- we should refile this in `sourcegraph/sourcegraph`.
