### ISSUE TITLE
Observable type in angular http.ts library appears clickable, but isn't

### ISSUE THREAD

**Issue by uforic** [sourcegraph/langserver-typescript#4]
https://sourcegraph.com/github.com/angular/angular/-/blob/modules/@angular/http/src/http.ts#L163

Click on Observable at the end of the line. Nothing happens!

Expected behavior - scroll to top of page, where Observable is imported.

https://cl.ly/3W1K1G3F1x2m

I'll also point out that the Observable at the top of the file isn't clickable, even though we can index RxJS where it's from and that file appears to work fine.

**Comment by rothfels** [comment]
@uforic this doesn't work in VSCode either; when that's the case, let's call it a feature not a bug.

**Comment by sqs** [comment]
> let's call it a feature not a bug

In these cases, when the fix would be to improve TypeScript's own language analysis, let's file it on the TypeScript repo and not here.
