### ISSUE TITLE
Imports not clickable in appbase file

### ISSUE THREAD

**Issue by uforic** [sourcegraph/langserver-typescript#5]
Repro:
https://sourcegraph.com/github.com/appbaseio/mirage/-/blob/app/shared/appbase.service.ts#L2

Click on "Headers", or "Http", or "Injectable"

None give J2D.

However, on another file, J2D does work:
https://sourcegraph.com/github.com/angular/angular/-/blob/modules/@angular/http/src/static_request.ts

Click on Body, ContentType, or another token along the top.

**Comment by alexsaveliev** [comment]
the difference between items you are trying to click in `mirage` repo and `angular` one is the following:

In `angular` imports refer to relative path to files in the same workspace while `mirage` refers to typings located in `node_modules` and supposed to be installed with `npm install`. We do not currently support fetching of typings from internet (this is what @antonina-cherednichenko is working on)

**Comment by sqs** [comment]
This is already WIP and well known, so closing
